name: macOS Build

on:
#  push:
#    branches: [ main ]
#  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  dummy:
    runs-on: macos-latest
    steps:
      - run: echo "Placeholder workflow"